version: "3.2"

services:

  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    volumes:
      - ./deployment/couchdb/couchdb_local.ini:/opt/couchdb/etc/local.ini
      - ./deployment/couchdb/data:/opt/couchdb/data
  redis:
    image: redis:7.0.12-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass YOURPASSWORD
    ports:
      - "6379:6379"
    volumes:
      - ./deployment/redis/data:/data

  mailio-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - couchserver
      - redis
    ports:
      - "8080:8080"
    environment:
      COUCH_DB_PASSWORD: YOURPASSWORD
      REDIS_PASSWORD: YOURPASSWORD
      SMTP_PASSWORD: YOURPASSWORD
      PROMETHEUS_PASSWORD: YOURPASSWORD
      AWS_SECRET: YOURPASSWORD
      AI_SEARCH_USERNAME: YOURUSERNAME
      AI_SEARCH_PASSWORD: YOURPASSWORD
    volumes:
      - ./conf.yaml:/app/config/conf.yaml