// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/handshake": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new handshake",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HANDSHAKE API"
                ],
                "summary": "Create a new handshake",
                "parameters": [
                    {
                        "description": "Handshake",
                        "name": "handshake",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Handshake"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.Handshake"
                        }
                    }
                }
            }
        },
        "/api/v1/handshake/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Returns a single handshake by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HANDSHAKE API"
                ],
                "summary": "Get handshake by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Handshake ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Handshake"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a handshake",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HANDSHAKE API"
                ],
                "summary": "Update a handshake",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Handshake ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Handshake",
                        "name": "handshake",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Handshake"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Handshake"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a handshake",
                "tags": [
                    "HANDSHAKE API"
                ],
                "summary": "Delete a handshake",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Handshake ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "Returns a JWS token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER ACCOUNT API"
                ],
                "summary": "Login with username and password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Handshake ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.JwsToken"
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "Returns a JWS token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER ACCOUNT API"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "email and password input",
                        "name": "emailPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.InputEmailPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.JwsToken"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Handshake": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "_rev": {
                    "description": "Rev is the revision number returned",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "rev": {
                    "type": "string"
                }
            }
        },
        "types.InputEmailPassword": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "types.JwsToken": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Mailio Server API",
	Description:      "Implements the Mailio server based on https://mirs.mail.io/ specifications",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
